#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later
# QuteTavern installer script:
#   1) check the system dependencies (prints hints, never runs sudo itself)
#   2) build the release binary with cmake
#   3) install the launcher script, the icon and the .desktop entry into the
#      user's home directory (no root required)
set -euo pipefail

cd "$(dirname "$0")"
PROJECT_DIR="$(pwd)"
BIN="$PROJECT_DIR/build/qutetavern"
DESKTOP_NAME="qutetavern"   # must match the Qt app_id (binary name) for task bar grouping

say()  { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
ok()   { printf '\033[1;32m ✓ \033[0m%s\n' "$*"; }
warn() { printf '\033[1;33m ! \033[0m%s\n' "$*"; }
fail() { printf '\033[1;31m ✗ \033[0m%s\n' "$*"; exit 1; }

# ---------- 1. dependency check ----------
say "Checking system dependencies..."
MISSING=()
command -v node  >/dev/null || MISSING+=("nodejs (Node.js >= 22)")
command -v npm   >/dev/null || MISSING+=("npm")
command -v git   >/dev/null || MISSING+=("git")
command -v cmake >/dev/null || MISSING+=("cmake")
command -v g++   >/dev/null || MISSING+=("g++")

if [ "${#MISSING[@]}" -gt 0 ]; then
    warn "Missing dependencies - install them and run this script again:"
    printf '      %s\n' "${MISSING[@]}"
    echo
    echo "  Fedora:        sudo dnf install nodejs npm git cmake gcc-c++"
    echo "  Debian/Ubuntu: sudo apt install nodejs npm git cmake g++"
    exit 1
fi
ok "Command line dependencies are complete"

# ---------- 2. build (also verifies the Qt development packages) ----------
say "Configuring with cmake (this also checks the Qt 6 development packages)..."
CONFIGURE_LOG="$PROJECT_DIR/build/configure.log"
mkdir -p "$PROJECT_DIR/build"
if ! cmake -B build -DCMAKE_BUILD_TYPE=Release >"$CONFIGURE_LOG" 2>&1; then
    warn "cmake configure failed - the Qt 6 development packages are most likely missing:"
    tail -n 20 "$CONFIGURE_LOG" || true
    echo
    echo "  Fedora:        sudo dnf install qt6-qtbase-devel qt6-qtwebengine-devel qt6-qtdeclarative-devel"
    echo "  Debian/Ubuntu: sudo apt install qt6-base-dev qt6-webengine-dev qt6-declarative-dev"
    exit 1
fi

say "Building the release binary..."
cmake --build build -j"$(nproc)" >/dev/null
[ -x "$BIN" ] || fail "The build finished but the binary is missing: $BIN"
ok "Build finished: $BIN"

# ---------- 3. install into the user's home directory ----------
say "Installing launcher / icon / .desktop entry..."

BIN_DIR="$HOME/.local/bin"
ICON_BASE="$HOME/.local/share/icons/hicolor"
APPS_DIR="$HOME/.local/share/applications"
mkdir -p "$BIN_DIR" "$APPS_DIR"

# Launcher script. The .desktop entry below starts it by absolute path; the
# app resolves node/git itself (with its login-shell PATH fallback), so no
# wrapper shell is needed.
cat > "$BIN_DIR/qutetavern" <<EOF
#!/usr/bin/env bash
# QuteTavern start script (generated by install.sh)
exec '$BIN' "\$@"
EOF
chmod +x "$BIN_DIR/qutetavern"

# Icon (multiple sizes)
for size in 32x32 64x64 128x128 256x256 512x512; do
    d="$ICON_BASE/$size/apps"
    mkdir -p "$d"
    cp -f "$PROJECT_DIR/resources/icon.png" "$d/qutetavern.png"
done

# .desktop entry: the same shape as the packaged one (absolute path, no shell
# wrapper) - PATH resolution happens inside the launcher
cat > "$APPS_DIR/$DESKTOP_NAME.desktop" <<EOF
[Desktop Entry]
Type=Application
Name=QuteTavern
GenericName=AI roleplay client
Comment=Start the QuteTavern desktop client for SillyTavern
Exec=$BIN_DIR/qutetavern
Icon=qutetavern
Terminal=false
Categories=Game;Network;
Keywords=AI;Roleplay;Chat;Tavern;
StartupWMClass=$DESKTOP_NAME
StartupNotify=true
EOF

update-desktop-database "$APPS_DIR" 2>/dev/null || true

ok "Installation finished:"
echo "    Application menu: QuteTavern (visible after a re-login or kbuildsycoca6)"
echo "    Command line    : ~/.local/bin/qutetavern"
echo "    Uninstall       : remove ~/.local/bin/qutetavern,"
echo "                      ~/.local/share/applications/$DESKTOP_NAME.desktop and"
echo "                      ~/.local/share/icons/hicolor/*/apps/qutetavern.png"